"""llm models and conversation model

Revision ID: 2cc4e6564e52
Revises: cc970e93590c
Create Date: 2026-10-05 18:57:08.735754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2cc4e6564e52'
down_revision: Union[str, None] = 'cc970e93590c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_models',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('api_base', sa.String(length=512), nullable=True),
    sa.Column('api_key', sa.String(length=512), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model')
    )
    op.add_column('conversations', sa.Column('model', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'model')
    op.drop_table('llm_models')
    # ### end Alembic commands ###
